### ISSUE TITLE
Finish prototype

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-azure-native#1]
The current implementation in this repo is a very rough prototype.  Some of the big missing pieces:

- [ ] Some solution to replacement #4
- [ ] Simplifying projection of ARM resources into  Pulumi schema (`x-ms-client-flatten`) #3
- [ ] Provider config and first-class providers #14
- [ ] Mapping of all ARM resource #12
- [ ] Validate inputs in Check against schema #6
- [ ] Code generation #9

And probably much, much more.
