### ISSUE TITLE
Arm2pulumi preview tracker

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-azure-native#210]
### Arm2pulumi page release checklist
- [x] Merge arm2pulumi to provider repo
- [x] ~~Cut new release of provider? Don't think its necessary though~~
- [x] Update https://github.com/pulumi/home/pull/1093 to use latest from upstream and get merged/deployed
- [x] Update front-end PR with more canned examples: https://github.com/pulumi/docs/pull/4284
- [x] Get docs PR merged https://github.com/pulumi/docs/pull/4284
- [x] Pick example workflow to demo in video - still looking to do this?

### Current known issues

 _High Priority_ 
- [x] Stack overflow with certain recursively defined types https://github.com/pulumi/pulumi/issues/5228
- [x] Nodejs program gen is adding an additional import line: `import * as azure_nextgen from "@pulumi/azure_nextgen";` (fixed by https://github.com/pulumi/pulumi/pull/5399)
 - [x] Golang codegen seems to be failing consistently since some schema changes
 - [x] Golang import seems incorrect since repo rename (PR here: https://github.com/pulumi/pulumi/pull/5415)
 - [x] Resource names should track what is in the template. Currently the variables and the names are derived from types and ignores the name in the template
 - [x] Resource group name config variable should be defined by default for all templates
 - [x] Some properties seem to be lost when converting (e.g. rancher template, https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-aci-linuxcontainer-public-ip/azuredeploy.json).
- [x] Number literals are being interpreted as strings (json.Number not being disambiguated in reflection)
- [x] Concat seems to be buggy
- [x] handle extensions
- [x] Redundant variables in generated code
- [x] Location missing 
- [ ] Backlinks from sub resources to parent is missing (affects resource exports). This can be iterated on after release?

 _Lower Priority_ 
- [ ] Add rudimentary resourceId support
- [x] nested resources are not being handled. Should at least provide a diagnostic for this.
- [ ] Need an invoke to get subscription information. https://github.com/pulumi/pulumi-azure-nextgen-provider/issues/181
