### ISSUE TITLE
[Epic] Azure Native V2

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-azure-native#2194]
## Overview

The primary goals for the next major version of Azure Native (V2) are:
- Reduce the size of SDKs, and so the size of related schemata
- Allow for a reasonably painless local development experience on the provider itself

## References

- [ ] PR/FAQ 
- [ ] Design Doc 
- [ ] [Roadmap](https://docs.google.com/document/d/18kbdhZJc2BRrm24CWalJGoCmYFv9JDyZWQx-kX6FHRs/edit#heading=h.p9oql9e433rm)

### Work Items ⚙️

- [ ] Data gathering / analysis for impact and feasibility of versions of resources which are removable, and for which resources a migration path exists
- [ ] Updates to schema-tools
- [ ] https://github.com/pulumi/pulumi-azure-native/issues/1324 (This _may_ be released separately but we should work with marketing to determine if it needs to be)

## Authentication

- [x] [OIDC Design](https://docs.google.com/document/d/1MvbucF5w2rwssTJKRQLut0wwm9OILk0PxLurWEEcy-g/edit)
- [ ] Implement design

**Comment by mnlumi** [comment]
Update: v2 has been [released](https://github.com/pulumi/pulumi-azure-native/releases/tag/v2.0.0) and is now generally available. Check out the [blog post](https://www.pulumi.com/blog/introducing-azure-native-v2/) and [upgrade guide](https://www.pulumi.com/registry/packages/azure-native/from-v1-to-v2/) for more info.

Current items remaining are post-release tasks including updates to documentation, examples, templates, etc.

**Comment by mnlumi** [comment]
Closing out the epic. Outstanding post-release tasks will be prioritized alongside other work.
