### ISSUE TITLE
arm2pulumi CLI release tracker

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-azure-native#262]
- [ ] Add project setup support to arm2pulumi
  - [ ] https://github.com/pulumi/pulumi/issues/4760
  - [x] Config support in Go codegen https://github.com/pulumi/pulumi/pull/5514 (In Review)
  - [x] https://github.com/pulumi/pulumi-azure-nextgen/issues/42
- [x] Update arm2pulumi web backend with latest
- [x] update the p.com/arm2pulumi page with latest
- [ ] Provider dumps metadata to stdout with a provided flag
- [ ] Update CLI to use provider to pull metadata and schema
- [ ] Seed separate repo and split code from provider repo
- [ ] Update CI to build and publish the arm2pulumi binary
- [ ] release arm2pulumi binary-only to get.pulumi.com

**Comment by mikhailshilkov** [comment]
This is likely out-of-date, closing for now
