### ISSUE TITLE
circular dependencies

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-azure-native#3090]
We've encountered a few different resources in Azure with circular dependencies and would like to develop a general solution

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/pulumi-azure-native/issues/578
- [ ] https://github.com/pulumi/pulumi-azure-native/issues/2617
- [ ] https://github.com/pulumi/pulumi-azure-native/issues/3143
```
